##############  mino分布式图片存储 ####################
file:
  upload-type: LOCAL 
  local:
    path: /Users/work/file/ # 本地上传文件到目录
  minio:
    end:
      point: http://dji-dev.com:9004
    accessKey: systemuser@dji.com
    secretKey: dji12345!@#




##############  fastdfs 配置  ####################
fastdfs:
  connect_timeout_in_seconds: 60
  network_timeout_in_seconds: 60
  charset: UTF-8
  http_tracker_http_port: 80
  http_anti_steal_token: false
  http_secret_key: dasjkdh239a1a97dpd1!@#
  tracker_servers: dji-dev.com:4443